# Generated by Django 5.0.7 on 2024-08-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('pet_description', models.CharField(max_length=30)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(default='TITLE', max_length=128, primary_key=True, serialize=False)),
                ('summary', models.CharField(default='SUMMARY', max_length=256)),
                ('date', models.CharField(default='DATE', max_length=128)),
                ('hyperlink', models.CharField(default='HYPERLINK', max_length=256)),
                ('created_on', models.CharField(max_length=34)),
            ],
        ),
    ]
